# Generated by Django 4.1.3 on 2022-12-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "store",
            "0004_rename_store_custo_last_na_e6a359_idx_store_custo_last_na_2e448d_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
