# Generated by Django 4.1.3 on 2022-12-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20221206_0505"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="collection",
            new_name="collection_id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
