# Generated by Django 4.1.3 on 2022-12-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_collection_product_collection_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="collection_id",
            new_name="collection",
        ),
    ]
