# Generated by Django 4.1.4 on 2022-12-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
